
### Register new User (Press on "Send Request" button below to make the call)
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "Interviewer",
  "email": "interview@gmail.com",
  "password": "interview123"
}

### Fetches all existing users
GET http://localhost:5000/api/auth/users
Authorization: Bearer <enter your jwt token in plain text here...>

### Login existing user and generates token
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "interview@gmail.com",
  "password": "interview123"
}

### Fetches all Auction Item for the user
GET http://localhost:5000/api/auction/
Authorization: Bearer <enter your jwt token in plain text here...>

### Creates new Auction Item. See the Example and remove the comment symbol to use it
POST http://localhost:5000/api/auction/create
Authorization: Bearer <enter your jwt token in plain text here...>
Content-Type: application/json

# {
#     "title":"Kodak Vintage Camera",
#     "image": "https://images.pexels.com/photos/51383/photo-camera-subject-photographer-51383.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
#     "description" :"This Kodak Vintage Camera is old but the most powerful camera you can have to take picturesque snapshots, videos, etc. This compact yet powerful camera offers full HD 1080p resolution, ensuring crystal-clear video quality, whether it's day or night. ",
#     "startingBid": 524,
#     "currentBid": 600,
#     "endDate": "2024-12-15"
# }

